// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MissIssippiAPI.Data;

#nullable disable

namespace MissIssippiAPI.Migrations
{
    [DbContext(typeof(MissIssippiContext))]
    [Migration("20260602193825_AddUserTableAndAuditFields")]
    partial class AddUserTableAndAuditFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MissIssippiAPI.Models.Collection", b =>
                {
                    b.Property<int>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollectionId"));

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.HasKey("CollectionId")
                        .HasName("PK__Collect__D1CCDFE1B35E33F2");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex(new[] { "CollectionName" }, "u_Collection_CollectionName")
                        .IsUnique();

                    b.ToTable("Collection", (string)null);
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"));

                    b.Property<int?>("CollectionId")
                        .HasColumnType("int");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("HexValue")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("PantoneColor")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("ColorId")
                        .HasName("PK__Color__8DA7674DAF1C0D00");

                    b.HasIndex("CollectionId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("SeasonId");

                    b.HasIndex(new[] { "ColorName", "SeasonId", "CollectionId" }, "u_Color_ColorName_SeasonId_CollectionId")
                        .IsUnique()
                        .HasFilter("[SeasonId] IS NOT NULL AND [CollectionId] IS NOT NULL");

                    b.ToTable("Color", (string)null);
                });

            modelBuilder.Entity("MissIssippiAPI.Models.ImageType", b =>
                {
                    b.Property<int>("ImageTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageTypeId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ImageTypeId")
                        .HasName("PK__ImageTyp__C4FE4B7B050E0A04");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex(new[] { "Sequence" }, "u_ImageType_Sequence")
                        .IsUnique();

                    b.HasIndex(new[] { "Type" }, "u_ImageType_Type")
                        .IsUnique();

                    b.ToTable("ImageType", (string)null);
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("InStock")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("(case when [Qty]>(0) then (1) else (0) end)", true);

                    b.Property<int>("ItemColorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("InventoryId")
                        .HasName("PK__Inventor__F5FDE6B312394863");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ItemColorId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("SizeId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("MissIssippiAPI.Models.InventoryActivityLog", b =>
                {
                    b.Property<int>("InventoryActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryActivityLogId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Delta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("InventoryActivityDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ItemColorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LogTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("NewQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("OldQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("InventoryActivityLogId")
                        .HasName("PK__Inventor__BE0F81F948B45064");

                    b.HasIndex("BatchId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ItemColorId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("SizeId");

                    b.ToTable("InventoryActivityLog", (string)null);
                });

            modelBuilder.Entity("MissIssippiAPI.Models.InventoryAdjustmentBatch", b =>
                {
                    b.Property<Guid>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTime>("BatchTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("BatchId")
                        .HasName("PK_InventoryAdjustmentBatch");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("InventoryAdjustmentBatch", (string)null);
                });

            modelBuilder.Entity("MissIssippiAPI.Models.InventoryUploadBatch", b =>
                {
                    b.Property<Guid>("UploadBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("CreatedInventory")
                        .HasColumnType("int");

                    b.Property<int>("CreatedItemColors")
                        .HasColumnType("int");

                    b.Property<int>("CreatedSkus")
                        .HasColumnType("int");

                    b.Property<string>("DatasetHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid?>("DuplicateOfUploadBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid?>("InventoryHistoryBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsUndone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("ProcessedRows")
                        .HasColumnType("int");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid?>("UndoHistoryBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UndoneAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedInventory")
                        .HasColumnType("int");

                    b.Property<int>("WarningCount")
                        .HasColumnType("int");

                    b.HasKey("UploadBatchId")
                        .HasName("PK_InventoryUploadBatch");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_InventoryUploadBatch_CreatedAt");

                    b.HasIndex(new[] { "DatasetHash", "Mode", "IsUndone" }, "ix_InventoryUploadBatch_Hash_Mode_Undone");

                    b.HasIndex(new[] { "IdempotencyKey" }, "u_InventoryUploadBatch_IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.ToTable("InventoryUploadBatch", (string)null);
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<decimal?>("CostPrice")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("InProduction")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ItemDateCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("WholesalePrice")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("ItemId")
                        .HasName("PK__Item__8AD14640BCF81361");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("SeasonId");

                    b.HasIndex(new[] { "ItemNumber", "SeasonId" }, "u_Item_ItemNumber_SeasonId")
                        .IsUnique();

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("MissIssippiAPI.Models.ItemColor", b =>
                {
                    b.Property<int>("ItemColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemColorId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("CompositeSignature")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.HasKey("ItemColorId")
                        .HasName("PK__ItemCol__D60ED5767E9873B1");

                    b.HasIndex("ColorId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex(new[] { "ItemId", "ColorId", "CompositeSignature" }, "u_ItemColor_ItemId_ColorId_CompositeSignature")
                        .IsUnique();

                    b.ToTable("ItemColor", (string)null);
                });

            modelBuilder.Entity("MissIssippiAPI.Models.ItemColorSecondaryColor", b =>
                {
                    b.Property<int>("ItemColorId")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryColorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("ItemColorId", "SecondaryColorId")
                        .HasName("PK_ItemColorSecondaryColor");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("SecondaryColorId");

                    b.ToTable("ItemColorSecondaryColor", (string)null);
                });

            modelBuilder.Entity("MissIssippiAPI.Models.ItemImage", b =>
                {
                    b.Property<int>("ItemImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemImageId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("ImageSequence")
                        .HasColumnType("int");

                    b.Property<int>("ImageSequenceWithinType")
                        .HasColumnType("int");

                    b.Property<int>("ImageTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ItemColorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.HasKey("ItemImageId")
                        .HasName("PK__ItemImag__7FBDF9E4A9A8D9E8");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ImageTypeId");

                    b.HasIndex("ItemColorId");

                    b.HasIndex("ModifiedByUserId");

                    b.ToTable("ItemImage", (string)null);
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeasonId"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("SeasonDateCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("SeasonId")
                        .HasName("PK__Season__C1814E3825F7E317");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex(new[] { "SeasonName" }, "u_Season_SeasonName")
                        .IsUnique();

                    b.ToTable("Season", (string)null);
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Size", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SizeSequence")
                        .HasColumnType("int");

                    b.HasKey("SizeId")
                        .HasName("PK__Sizes__83BD097A09B4478E");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex(new[] { "SizeName" }, "u_Sizes_SizeName")
                        .IsUnique();

                    b.HasIndex(new[] { "SizeSequence" }, "u_Sizes_Size_Sequence")
                        .IsUnique();

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Sku", b =>
                {
                    b.Property<int>("SkuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkuId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("ItemColorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.Property<string>("SkuValue")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("Sku");

                    b.HasKey("SkuId")
                        .HasName("PK__Sku__CA1ECF0D968C4D01");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("SizeId");

                    b.HasIndex(new[] { "ItemColorId", "SizeId" }, "u_Sku_ItemColorId_SizeId")
                        .IsUnique();

                    b.HasIndex(new[] { "SkuValue" }, "u_Sku_Sku")
                        .IsUnique();

                    b.ToTable("Sku", (string)null);
                });

            modelBuilder.Entity("MissIssippiAPI.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("owner");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Collection", b =>
                {
                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Color", b =>
                {
                    b.HasOne("MissIssippiAPI.Models.Collection", "Collection")
                        .WithMany("Colors")
                        .HasForeignKey("CollectionId")
                        .HasConstraintName("f_Collection_Color");

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("f_Season_Color");

                    b.Navigation("Collection");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MissIssippiAPI.Models.ImageType", b =>
                {
                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Inventory", b =>
                {
                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.ItemColor", "ItemColor")
                        .WithMany("Inventories")
                        .HasForeignKey("ItemColorId")
                        .IsRequired()
                        .HasConstraintName("f_ItemColor_Inventory");

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.Size", "Size")
                        .WithMany("Inventories")
                        .HasForeignKey("SizeId")
                        .IsRequired()
                        .HasConstraintName("f_Sizes_Inventory");

                    b.Navigation("ItemColor");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("MissIssippiAPI.Models.InventoryActivityLog", b =>
                {
                    b.HasOne("MissIssippiAPI.Models.InventoryAdjustmentBatch", "Batch")
                        .WithMany("InventoryActivityLogs")
                        .HasForeignKey("BatchId")
                        .IsRequired()
                        .HasConstraintName("f_InventoryAdjustmentBatch_InventoryActivityLog");

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.ItemColor", "ItemColor")
                        .WithMany("InventoryActivityLogs")
                        .HasForeignKey("ItemColorId")
                        .IsRequired()
                        .HasConstraintName("f_ItemColor_InventoryActivityLog");

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.Size", "Size")
                        .WithMany("InventoryActivityLogs")
                        .HasForeignKey("SizeId")
                        .IsRequired()
                        .HasConstraintName("f_Sizes_InventoryActivityLog");

                    b.Navigation("Batch");

                    b.Navigation("ItemColor");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("MissIssippiAPI.Models.InventoryAdjustmentBatch", b =>
                {
                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MissIssippiAPI.Models.InventoryUploadBatch", b =>
                {
                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Item", b =>
                {
                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.Season", "Season")
                        .WithMany("Items")
                        .HasForeignKey("SeasonId")
                        .IsRequired()
                        .HasConstraintName("f_Season_Item");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MissIssippiAPI.Models.ItemColor", b =>
                {
                    b.HasOne("MissIssippiAPI.Models.Color", "Color")
                        .WithMany("ItemColors")
                        .HasForeignKey("ColorId")
                        .IsRequired()
                        .HasConstraintName("f_Color_ItemColor");

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.Item", "Item")
                        .WithMany("ItemColors")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("f_Item_ItemColor");

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MissIssippiAPI.Models.ItemColorSecondaryColor", b =>
                {
                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.ItemColor", "ItemColor")
                        .WithMany("ItemColorSecondaryColors")
                        .HasForeignKey("ItemColorId")
                        .IsRequired()
                        .HasConstraintName("f_ItemColor_ItemColorSecondaryColor");

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.Color", "SecondaryColor")
                        .WithMany("ItemColorSecondaryColors")
                        .HasForeignKey("SecondaryColorId")
                        .IsRequired()
                        .HasConstraintName("f_Color_ItemColorSecondaryColor");

                    b.Navigation("ItemColor");

                    b.Navigation("SecondaryColor");
                });

            modelBuilder.Entity("MissIssippiAPI.Models.ItemImage", b =>
                {
                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.ImageType", "ImageType")
                        .WithMany("ItemImages")
                        .HasForeignKey("ImageTypeId")
                        .IsRequired()
                        .HasConstraintName("f_ImageType_ItemImage");

                    b.HasOne("MissIssippiAPI.Models.ItemColor", "ItemColor")
                        .WithMany("ItemImages")
                        .HasForeignKey("ItemColorId")
                        .IsRequired()
                        .HasConstraintName("f_ItemColor_ItemImage");

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ImageType");

                    b.Navigation("ItemColor");
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Season", b =>
                {
                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Size", b =>
                {
                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Sku", b =>
                {
                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.ItemColor", "ItemColor")
                        .WithMany("Skus")
                        .HasForeignKey("ItemColorId")
                        .IsRequired()
                        .HasConstraintName("f_ItemColor_Sku");

                    b.HasOne("MissIssippiAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MissIssippiAPI.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .IsRequired()
                        .HasConstraintName("f_Sizes_Sku");

                    b.Navigation("ItemColor");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Collection", b =>
                {
                    b.Navigation("Colors");
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Color", b =>
                {
                    b.Navigation("ItemColorSecondaryColors");

                    b.Navigation("ItemColors");
                });

            modelBuilder.Entity("MissIssippiAPI.Models.ImageType", b =>
                {
                    b.Navigation("ItemImages");
                });

            modelBuilder.Entity("MissIssippiAPI.Models.InventoryAdjustmentBatch", b =>
                {
                    b.Navigation("InventoryActivityLogs");
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Item", b =>
                {
                    b.Navigation("ItemColors");
                });

            modelBuilder.Entity("MissIssippiAPI.Models.ItemColor", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("InventoryActivityLogs");

                    b.Navigation("ItemColorSecondaryColors");

                    b.Navigation("ItemImages");

                    b.Navigation("Skus");
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Season", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MissIssippiAPI.Models.Size", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("InventoryActivityLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
